language: python
python:
  - "2.6"
  - "2.7"

# install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -e ."

# run 
script: make deb 

# setup notifications
notifications:
  irc:
    channels: "irc.freenode.org#cloudant-dev"
    on_success: change
    on_failure: change
  email: false
